[package]
name = "cw-rate-limiter"
license = "BSD-3"
authors = ["ekez <ekez@withoutdoing.com>"]
edition = "2021"
version = "0.0.1"

[dependencies]
cosmwasm-std = "1.1.1"
cosmwasm-schema = "1.1.1"
cw-storage-plus = "0.15.0"
thiserror = { version = "1" }
