[package]
name = "cw721-outgoing-proxy"
license = "BSD-3"
authors = ["ekez <ekez@withoutdoing.com>", "mr-t <mr-t@arkprotocol.io>"]
edition = "2021"
version = "0.0.1"

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }

cw-storage-plus = { workspace = true }
cw721 = { workspace = true }

thiserror = { workspace = true }

cw721-outgoing-proxy-derive = { workspace = true }