[package]
name = "cw-ics721-outgoing-proxy"
license = "BSD-3"
authors = ["ekez <ekez@withoutdoing.com>", "mr-t <mr-t@arkprotocol.io>"]
edition = "2021"
version = "0.1.0"

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }

cw-storage-plus = { workspace = true }
cw721 = { workspace = true }
cw721-base = { workspace = true }
ics721-types = { workspace = true }

thiserror = { workspace = true }

cw-ics721-outgoing-proxy-derive = { workspace = true }