[package]
name         = "cw-ics721-incoming-proxy-derive"
version      = "0.1.0"
description  = "Contains `ics721_incoming_proxy_execute` and `ics721_incoming_proxy_query` macros for generating ICS721 Context-based contracts."
license      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
keywords     = { workspace = true }

[lib]
doctest      = false # disable doc tests
proc-macro   = true

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
ics721-types = { workspace = true }
proc-macro2  = { workspace = true }
quote        = { workspace = true }
syn          = { workspace = true }
