[package]
name = "ibc-outgoing-msg"
license = "BSD-3"
authors = ["Mr T <mr-t@arkprotocol.io>"]
edition = "2021"
version = "0.0.1"

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
