[package]
name = "cw721-proxy-derive"
license = "BSD-3"
authors = ["ekez <ekez@withoutdoing.com>"]
edition = "2021"
version = "0.0.1"

[lib]
proc-macro = true

[dependencies]
cw721 = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
